create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null,
  category text not null default 'Hukuk Notları',
  language text not null default 'tr' check (language in ('tr', 'ru', 'en', 'ro')),
  status text not null default 'draft' check (status in ('draft', 'published')),
  author_id uuid not null references auth.users(id),
  author_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

alter table public.admin_users enable row level security;
alter table public.posts enable row level security;

drop policy if exists "Administrators can read their membership" on public.admin_users;
drop policy if exists "Published posts are public" on public.posts;
drop policy if exists "Administrators can read all posts" on public.posts;
drop policy if exists "Administrators can create posts" on public.posts;
drop policy if exists "Administrators can update posts" on public.posts;
drop policy if exists "Administrators can delete posts" on public.posts;

create policy "Administrators can read their membership" on public.admin_users
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Published posts are public" on public.posts
  for select to anon, authenticated using (status = 'published');
create policy "Administrators can read all posts" on public.posts
  for select to authenticated using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Administrators can create posts" on public.posts
  for insert to authenticated with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())) and author_id = (select auth.uid()));
create policy "Administrators can update posts" on public.posts
  for update to authenticated using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Administrators can delete posts" on public.posts
  for delete to authenticated using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

grant select on public.posts to anon;
grant select, insert, update, delete on public.posts to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on sequence public.posts_id_seq to authenticated;

-- İlk kullanıcıyı Authentication > Users bölümünde oluşturduktan sonra e-posta adresini değiştirip çalıştırın:
-- insert into public.admin_users (user_id, email)
-- select id, email from auth.users where email = 'avukat@example.com';
