export type SiteLanguage = "tr" | "ru" | "en" | "ro";

const en: Record<string, string> = {
  "Ana menü": "Main menu", "Menüyü aç": "Open menu", "Menü": "Menu", "Çalışma Alanları": "Practice Areas", "Çalışma alanları": "Practice areas", "Avukat": "Lawyer", "Hukuk Notları": "Legal Notes", "İletişim": "Contact",
  "Antalya Barosu": "Antalya Bar Association", "İçerikler genel bilgilendirme amaçlıdır.": "Content is provided for general information only.",
  "Hukukun yabancı": "A place where the law", "dilde kalmadığı bir yer.": "is never a foreign language.", "Türkiye’de yaşayan, yatırım yapan ve iş kuran yabancılar için çok dilli hukuk hizmeti.": "Multilingual legal services for foreigners living, investing and doing business in Türkiye.",
  "Bilgi · Tecrübe · Dikkat": "Knowledge · Experience · Care", "Her dosya, kendi": "Every matter is assessed", "koşullarıyla değerlendirilir.": "on its own circumstances.", "Hazır cevaplar yerine dosyanın gerçeğine, hedeflerine ve risklerine odaklanan kişisel çalışma.": "A personal approach focused on the facts, objectives and risks of each matter—not ready-made answers.",
  "Türkiye’de hukuki süreçler,": "Legal processes in Türkiye,", "kendi dilinizde.": "in your own language.", "Yerel hukuk bilgisini uluslararası bakışla birleştiren, doğrudan ve anlaşılır iletişim.": "Clear, direct communication combining local legal knowledge with an international outlook.",
  "Büroyu tanıyın": "Discover the practice", "Hukuki öngörü": "Legal foresight", "Çok dilli iletişim": "Multilingual communication", "Uluslararası bakış": "International outlook", "Yerel tecrübe": "Local experience", "Yaklaşım": "Approach",
  "Yabancı olduğunuz bir ülkede,": "In a country that is foreign to you,", "hukuki süreç": "the legal process", "yabancı kalmasın.": "should not feel foreign.", "Av. Ruslana Pasecinic; Türkiye’de yaşayan, yatırım yapan ve iş kuran yabancıların hukuki meselelerini dört dilde, doğrudan ve özenle takip eder.": "Atty. Ruslana Pasecinic handles the legal matters of foreigners living, investing and doing business in Türkiye with care, direct communication and service in four languages.", "Avukat hakkında": "About the lawyer",
  "Gayrimenkulden ticarete, göçten mirasa uzanan çok yönlü hukuk hizmetleri.": "Multidisciplinary legal services spanning real estate, commerce, immigration and inheritance.", "İnceleyin": "Explore", "Doğrudan iletişim, çok dilli çalışma ve dosyaya özel hukuki yaklaşım.": "Direct communication, multilingual service and a matter-specific legal approach.", "Tanıyın": "Meet", "Türkiye’de yaşam, yatırım ve iş için anlaşılır güncel hukuk yazıları.": "Clear, current legal articles for life, investment and business in Türkiye.", "Okuyun": "Read",
  "Son hukuk notları": "Latest legal notes", "Güncel meseleler,": "Current issues,", "açık anlatımla.": "explained clearly.", "Tüm yazılar": "All articles",
  "Uzmanlıklar": "Expertise", "Hukuki ihtiyaçlar,": "Legal needs,", "bütüncül bir bakışla.": "viewed as a whole.", "Türkiye ile bağlantılı özel ve ticari meselelerde, dosyanın tamamını gören bir çalışma.": "A comprehensive approach to private and commercial matters connected with Türkiye.", "Her hukuki süreç tek bir başlıktan ibaret değildir. Taşınmaz alımı ikamet ve vatandaşlıkla; şirket kuruluşu sözleşmeler ve çalışma izinleriyle; aile ve miras dosyaları ise birden fazla ülkenin hukukuyla kesişebilir. Çalışma, bu bağlantılar birlikte değerlendirilerek yürütülür.": "A legal process rarely belongs to a single category. Property acquisition may intersect with residence and citizenship; company formation with contracts and work permits; family and inheritance matters with the laws of several countries. These connections are considered together.",
  "Gayrimenkul & Yatırım": "Real Estate & Investment", "Şirketler & Ticaret": "Corporate & Commercial", "Göç & Vatandaşlık": "Immigration & Citizenship", "Aile & Miras": "Family & Inheritance", "Dava & Uyuşmazlık": "Litigation & Disputes", "Kaza & Tazminat": "Accidents & Compensation",
  "Satın alma, tapu incelemesi, vatandaşlık yatırımı ve uyuşmazlık yönetimi.": "Acquisitions, title deed review, citizenship investment and dispute management.", "Şirket kuruluşu, sözleşmeler, ortaklık yapıları ve sınır ötesi ticari süreçler.": "Company formation, contracts, partnership structures and cross-border commercial processes.", "İkamet, çalışma izni, vatandaşlık başvurusu ve idari süreçlerin takibi.": "Residence, work permits, citizenship applications and administrative proceedings.", "Uluslararası aile dosyaları, velayet, boşanma, miras ve veraset işlemleri.": "International family matters, custody, divorce, inheritance and succession.", "Mahkeme ve icra süreçlerinde stratejik temsil, müzakere ve çözüm.": "Strategic representation, negotiation and resolution in court and enforcement proceedings.", "Trafik kazaları, sigorta dosyaları ve maddi-manevi tazminat talepleri.": "Traffic accidents, insurance matters and pecuniary or non-pecuniary compensation claims.",
  "Avukat · Antalya Barosu": "Lawyer · Antalya Bar Association", "Türkiye’de hukuk,": "Law in Türkiye,", "Hukuki bir mesele, kişinin bilmediği bir ülkede ve yabancı bir dilde yürüdüğünde olduğundan daha karmaşık görünebilir. Av. Ruslana Pasecinic’in çalışma yaklaşımı, bu karmaşıklığı anlaşılır bir sürece dönüştürmek üzerine kuruludur.": "A legal matter can appear more complex when it unfolds in an unfamiliar country and language. Atty. Ruslana Pasecinic’s approach is built on turning that complexity into a process that can be understood.", "Türkiye’de yaşayan, çalışan, yatırım yapan veya burada malvarlığı bulunan yabancı müvekkillerle doğrudan iletişim kurar; dosyanın hukuki yönünü, olası riskleri ve izlenecek adımları açık biçimde aktarır.": "She communicates directly with foreign clients who live, work, invest or own assets in Türkiye, clearly explaining the legal aspects, potential risks and next steps.", "Gayrimenkul, ticaret, göç, aile, miras ve uyuşmazlık dosyalarında; farklı hukuk alanlarının birbiriyle kesiştiği noktaları birlikte değerlendirir. Amaç yalnızca işlemi tamamlamak değil, müvekkilin kararını hukuken sağlam bir zemine oturtmaktır.": "In real estate, commercial, immigration, family, inheritance and dispute matters, she considers how different fields of law intersect. The aim is not merely to complete a transaction, but to place the client’s decision on sound legal ground.", "“Müvekkilin süreci anlaması, doğru hukuki stratejinin ayrılmaz bir parçasıdır.”": "“A client’s understanding of the process is an inseparable part of sound legal strategy.”",
  "Doğrudan iletişim": "Direct communication", "Dosyanın her aşamasında avukatla doğrudan ve kendi dilinizde iletişim.": "Direct communication with your lawyer, in your own language, at every stage.", "Özenli inceleme": "Careful review", "Hazır şablonlar yerine olayın kendisine ve belgelere dayanan değerlendirme.": "Assessment based on the facts and documents rather than ready-made templates.", "Çok yönlü bakış": "Multidisciplinary perspective", "Türkiye hukuku ile sınır ötesi sonuçları birlikte ele alan dosya yönetimi.": "Matter management that considers Turkish law together with cross-border consequences.",
  "Bilgi, doğru kararın başlangıcıdır.": "Knowledge is the beginning of a sound decision.", "Hukuku daha": "Making the law", "anlaşılır kılmak.": "easier to understand.", "Türkiye’de yaşam, yatırım ve ticaret için güncel, sade ve uygulanabilir hukuk notları.": "Current, clear and practical legal notes for life, investment and business in Türkiye.", "Tümü": "All", "Yayında": "Published", "Taslak": "Draft",
  "Antalya’da,": "In Antalya,", "Türkiye’nin her yerinde.": "across Türkiye.", "Telefon": "Telephone", "E-posta": "Email", "Adres": "Address", "Diller": "Languages", "Ofis konumu": "Office location", "Google Haritalar’da aç": "Open in Google Maps",
  "Tapu ve hukuki durum incelemesi": "Title deed and legal status review", "Satış ve yatırım sözleşmeleri": "Sale and investment agreements", "Yatırım yoluyla vatandaşlık": "Citizenship by investment", "Şirket kuruluşu ve ortaklık yapısı": "Company formation and partnership structure", "Ticari sözleşmeler": "Commercial contracts", "Uyuşmazlık ve alacak takibi": "Dispute and debt recovery", "İkamet ve çalışma izinleri": "Residence and work permits", "Vatandaşlık başvuruları": "Citizenship applications", "İdari başvuru ve itirazlar": "Administrative applications and appeals", "Uluslararası boşanma ve velayet": "International divorce and custody", "Mirasçılık ve intikal işlemleri": "Succession and transfer procedures", "Yabancı kararların tanınması": "Recognition of foreign judgments", "Hukuk ve ticaret davaları": "Civil and commercial litigation", "İcra ve alacak takibi": "Enforcement and debt recovery", "Müzakere ve arabuluculuk": "Negotiation and mediation", "Trafik kazaları": "Traffic accidents", "Sigorta ve tazminat talepleri": "Insurance and compensation claims", "Zarar hesabı ve takip": "Loss assessment and claims handling",
};

const ru: Record<string, string> = {
  "Ana menü": "Главное меню", "Menüyü aç": "Открыть меню", "Menü": "Меню", "Çalışma Alanları": "Практики", "Çalışma alanları": "Практики", "Avukat": "Адвокат", "Hukuk Notları": "Правовые заметки", "İletişim": "Контакты",
  "Antalya Barosu": "Адвокатская палата Антальи", "İçerikler genel bilgilendirme amaçlıdır.": "Материалы носят общий информационный характер.",
  "Hukukun yabancı": "Место, где право", "dilde kalmadığı bir yer.": "говорит на вашем языке.", "Türkiye’de yaşayan, yatırım yapan ve iş kuran yabancılar için çok dilli hukuk hizmeti.": "Многоязычные юридические услуги для иностранцев, живущих, инвестирующих и ведущих бизнес в Турции.",
  "Bilgi · Tecrübe · Dikkat": "Знания · Опыт · Внимание", "Her dosya, kendi": "Каждое дело оценивается", "koşullarıyla değerlendirilir.": "с учётом его обстоятельств.", "Hazır cevaplar yerine dosyanın gerçeğine, hedeflerine ve risklerine odaklanan kişisel çalışma.": "Индивидуальная работа с учётом фактов, целей и рисков конкретного дела — без шаблонных ответов.",
  "Türkiye’de hukuki süreçler,": "Юридические процессы в Турции —", "kendi dilinizde.": "на вашем языке.", "Yerel hukuk bilgisini uluslararası bakışla birleştiren, doğrudan ve anlaşılır iletişim.": "Прямое и понятное общение, объединяющее знание местного права с международным взглядом.",
  "Büroyu tanıyın": "О бюро", "Hukuki öngörü": "Правовая предусмотрительность", "Çok dilli iletişim": "Многоязычное общение", "Uluslararası bakış": "Международный взгляд", "Yerel tecrübe": "Местный опыт", "Yaklaşım": "Подход",
  "Yabancı olduğunuz bir ülkede,": "В незнакомой вам стране", "hukuki süreç": "юридический процесс", "yabancı kalmasın.": "не должен оставаться чужим.", "Av. Ruslana Pasecinic; Türkiye’de yaşayan, yatırım yapan ve iş kuran yabancıların hukuki meselelerini dört dilde, doğrudan ve özenle takip eder.": "Адвокат Руслана Пасечиник внимательно и напрямую ведёт на четырёх языках юридические дела иностранцев, живущих, инвестирующих и ведущих бизнес в Турции.", "Avukat hakkında": "Об адвокате",
  "Gayrimenkulden ticarete, göçten mirasa uzanan çok yönlü hukuk hizmetleri.": "Комплексные юридические услуги: от недвижимости и бизнеса до миграции и наследства.", "İnceleyin": "Подробнее", "Doğrudan iletişim, çok dilli çalışma ve dosyaya özel hukuki yaklaşım.": "Прямое общение, работа на нескольких языках и индивидуальный подход к каждому делу.", "Tanıyın": "Познакомиться", "Türkiye’de yaşam, yatırım ve iş için anlaşılır güncel hukuk yazıları.": "Понятные актуальные материалы о жизни, инвестициях и бизнесе в Турции.", "Okuyun": "Читать",
  "Son hukuk notları": "Последние правовые заметки", "Güncel meseleler,": "Актуальные вопросы —", "açık anlatımla.": "понятным языком.", "Tüm yazılar": "Все статьи",
  "Uzmanlıklar": "Практики", "Hukuki ihtiyaçlar,": "Правовые задачи —", "bütüncül bir bakışla.": "с комплексным подходом.", "Türkiye ile bağlantılı özel ve ticari meselelerde, dosyanın tamamını gören bir çalışma.": "Комплексная работа по частным и коммерческим вопросам, связанным с Турцией.", "Her hukuki süreç tek bir başlıktan ibaret değildir. Taşınmaz alımı ikamet ve vatandaşlıkla; şirket kuruluşu sözleşmeler ve çalışma izinleriyle; aile ve miras dosyaları ise birden fazla ülkenin hukukuyla kesişebilir. Çalışma, bu bağlantılar birlikte değerlendirilerek yürütülür.": "Юридический процесс редко ограничивается одной областью. Покупка недвижимости может быть связана с ВНЖ и гражданством, создание компании — с договорами и разрешениями на работу, а семейные и наследственные дела — с правом нескольких стран. Все эти связи рассматриваются в комплексе.",
  "Gayrimenkul & Yatırım": "Недвижимость и инвестиции", "Şirketler & Ticaret": "Корпоративное и торговое право", "Göç & Vatandaşlık": "Миграция и гражданство", "Aile & Miras": "Семейное и наследственное право", "Dava & Uyuşmazlık": "Суды и споры", "Kaza & Tazminat": "ДТП и компенсации",
  "Satın alma, tapu incelemesi, vatandaşlık yatırımı ve uyuşmazlık yönetimi.": "Покупка, проверка титула, инвестиции для гражданства и ведение споров.", "Şirket kuruluşu, sözleşmeler, ortaklık yapıları ve sınır ötesi ticari süreçler.": "Создание компаний, договоры, партнёрские структуры и трансграничные коммерческие процессы.", "İkamet, çalışma izni, vatandaşlık başvurusu ve idari süreçlerin takibi.": "ВНЖ, разрешения на работу, заявления на гражданство и административные процедуры.", "Uluslararası aile dosyaları, velayet, boşanma, miras ve veraset işlemleri.": "Международные семейные дела, опека, развод, наследство и оформление прав.", "Mahkeme ve icra süreçlerinde stratejik temsil, müzakere ve çözüm.": "Стратегическое представительство, переговоры и урегулирование в судебных и исполнительных процессах.", "Trafik kazaları, sigorta dosyaları ve maddi-manevi tazminat talepleri.": "ДТП, страховые дела и требования о материальной и моральной компенсации.",
  "Avukat · Antalya Barosu": "Адвокат · Палата адвокатов Антальи", "Türkiye’de hukuk,": "Право в Турции —", "Hukuki bir mesele, kişinin bilmediği bir ülkede ve yabancı bir dilde yürüdüğünde olduğundan daha karmaşık görünebilir. Av. Ruslana Pasecinic’in çalışma yaklaşımı, bu karmaşıklığı anlaşılır bir sürece dönüştürmek üzerine kuruludur.": "Юридический вопрос может казаться сложнее, если он решается в незнакомой стране и на чужом языке. Подход адвоката Русланы Пасечиник основан на том, чтобы превратить эту сложность в понятный процесс.", "Türkiye’de yaşayan, çalışan, yatırım yapan veya burada malvarlığı bulunan yabancı müvekkillerle doğrudan iletişim kurar; dosyanın hukuki yönünü, olası riskleri ve izlenecek adımları açık biçimde aktarır.": "Она напрямую общается с иностранными клиентами, которые живут, работают, инвестируют или владеют активами в Турции, ясно разъясняя правовую сторону дела, возможные риски и дальнейшие шаги.", "Gayrimenkul, ticaret, göç, aile, miras ve uyuşmazlık dosyalarında; farklı hukuk alanlarının birbiriyle kesiştiği noktaları birlikte değerlendirir. Amaç yalnızca işlemi tamamlamak değil, müvekkilin kararını hukuken sağlam bir zemine oturtmaktır.": "В делах о недвижимости, бизнесе, миграции, семье, наследстве и спорах учитывается взаимосвязь разных областей права. Цель — не просто завершить процедуру, а обеспечить решению клиента прочную правовую основу.", "“Müvekkilin süreci anlaması, doğru hukuki stratejinin ayrılmaz bir parçasıdır.”": "«Понимание клиентом процесса — неотъемлемая часть правильной правовой стратегии».",
  "Doğrudan iletişim": "Прямое общение", "Dosyanın her aşamasında avukatla doğrudan ve kendi dilinizde iletişim.": "Прямое общение с адвокатом на вашем языке на каждом этапе дела.", "Özenli inceleme": "Тщательный анализ", "Hazır şablonlar yerine olayın kendisine ve belgelere dayanan değerlendirme.": "Оценка на основе обстоятельств и документов, а не готовых шаблонов.", "Çok yönlü bakış": "Комплексный взгляд", "Türkiye hukuku ile sınır ötesi sonuçları birlikte ele alan dosya yönetimi.": "Ведение дела с учётом турецкого права и трансграничных последствий.",
  "Bilgi, doğru kararın başlangıcıdır.": "Знание — начало верного решения.", "Hukuku daha": "Право —", "anlaşılır kılmak.": "понятным языком.", "Türkiye’de yaşam, yatırım ve ticaret için güncel, sade ve uygulanabilir hukuk notları.": "Актуальные, ясные и практичные правовые заметки о жизни, инвестициях и бизнесе в Турции.", "Tümü": "Все", "Yayında": "Опубликовано", "Taslak": "Черновик",
  "Antalya’da,": "В Анталье —", "Türkiye’nin her yerinde.": "по всей Турции.", "Telefon": "Телефон", "E-posta": "Эл. почта", "Adres": "Адрес", "Diller": "Языки", "Ofis konumu": "Расположение офиса", "Google Haritalar’da aç": "Открыть в Google Картах",
};

const ro: Record<string, string> = {
  "Ana menü": "Meniu principal", "Menüyü aç": "Deschide meniul", "Menü": "Meniu", "Çalışma Alanları": "Domenii de practică", "Çalışma alanları": "Domenii de practică", "Avukat": "Avocat", "Hukuk Notları": "Note juridice", "İletişim": "Contact",
  "Antalya Barosu": "Baroul Antalya", "İçerikler genel bilgilendirme amaçlıdır.": "Conținutul are exclusiv scop informativ general.",
  "Hukukun yabancı": "Un loc în care dreptul", "dilde kalmadığı bir yer.": "vorbește limba dumneavoastră.", "Türkiye’de yaşayan, yatırım yapan ve iş kuran yabancılar için çok dilli hukuk hizmeti.": "Servicii juridice multilingve pentru străinii care locuiesc, investesc și desfășoară afaceri în Turcia.",
  "Bilgi · Tecrübe · Dikkat": "Cunoaștere · Experiență · Atenție", "Her dosya, kendi": "Fiecare dosar este analizat", "koşullarıyla değerlendirilir.": "în propriul său context.", "Hazır cevaplar yerine dosyanın gerçeğine, hedeflerine ve risklerine odaklanan kişisel çalışma.": "O abordare personalizată, concentrată pe faptele, obiectivele și riscurile fiecărui dosar, nu pe răspunsuri standard.",
  "Türkiye’de hukuki süreçler,": "Proceduri juridice în Turcia,", "kendi dilinizde.": "în limba dumneavoastră.", "Yerel hukuk bilgisini uluslararası bakışla birleştiren, doğrudan ve anlaşılır iletişim.": "Comunicare directă și clară, care îmbină cunoașterea dreptului local cu o perspectivă internațională.",
  "Büroyu tanıyın": "Descoperiți cabinetul", "Hukuki öngörü": "Previziune juridică", "Çok dilli iletişim": "Comunicare multilingvă", "Uluslararası bakış": "Perspectivă internațională", "Yerel tecrübe": "Experiență locală", "Yaklaşım": "Abordare",
  "Yabancı olduğunuz bir ülkede,": "Într-o țară care vă este străină,", "hukuki süreç": "procesul juridic", "yabancı kalmasın.": "nu trebuie să rămână străin.", "Av. Ruslana Pasecinic; Türkiye’de yaşayan, yatırım yapan ve iş kuran yabancıların hukuki meselelerini dört dilde, doğrudan ve özenle takip eder.": "Av. Ruslana Pasecinic gestionează cu atenție și comunicare directă, în patru limbi, problemele juridice ale străinilor care locuiesc, investesc și desfășoară afaceri în Turcia.", "Avukat hakkında": "Despre avocat",
  "Gayrimenkulden ticarete, göçten mirasa uzanan çok yönlü hukuk hizmetleri.": "Servicii juridice multidisciplinare, de la imobiliare și comerț până la imigrare și moșteniri.", "İnceleyin": "Descoperiți", "Doğrudan iletişim, çok dilli çalışma ve dosyaya özel hukuki yaklaşım.": "Comunicare directă, servicii multilingve și o abordare juridică adaptată fiecărui dosar.", "Tanıyın": "Cunoașteți", "Türkiye’de yaşam, yatırım ve iş için anlaşılır güncel hukuk yazıları.": "Articole juridice actuale și clare pentru viață, investiții și afaceri în Turcia.", "Okuyun": "Citiți",
  "Son hukuk notları": "Ultimele note juridice", "Güncel meseleler,": "Subiecte actuale,", "açık anlatımla.": "explicate clar.", "Tüm yazılar": "Toate articolele",
  "Uzmanlıklar": "Expertiză", "Hukuki ihtiyaçlar,": "Nevoi juridice,", "bütüncül bir bakışla.": "privite în ansamblu.", "Türkiye ile bağlantılı özel ve ticari meselelerde, dosyanın tamamını gören bir çalışma.": "O abordare completă a chestiunilor private și comerciale legate de Turcia.", "Her hukuki süreç tek bir başlıktan ibaret değildir. Taşınmaz alımı ikamet ve vatandaşlıkla; şirket kuruluşu sözleşmeler ve çalışma izinleriyle; aile ve miras dosyaları ise birden fazla ülkenin hukukuyla kesişebilir. Çalışma, bu bağlantılar birlikte değerlendirilerek yürütülür.": "Un proces juridic rareori aparține unui singur domeniu. Achiziția imobiliară se poate intersecta cu rezidența și cetățenia; înființarea unei companii, cu contractele și permisele de muncă; iar dosarele de familie și moștenire, cu legislația mai multor state. Aceste legături sunt analizate împreună.",
  "Gayrimenkul & Yatırım": "Imobiliare și investiții", "Şirketler & Ticaret": "Drept corporativ și comercial", "Göç & Vatandaşlık": "Imigrare și cetățenie", "Aile & Miras": "Familie și moșteniri", "Dava & Uyuşmazlık": "Litigii și dispute", "Kaza & Tazminat": "Accidente și despăgubiri",
  "Satın alma, tapu incelemesi, vatandaşlık yatırımı ve uyuşmazlık yönetimi.": "Achiziții, verificarea titlului, investiții pentru cetățenie și gestionarea litigiilor.", "Şirket kuruluşu, sözleşmeler, ortaklık yapıları ve sınır ötesi ticari süreçler.": "Înființarea companiilor, contracte, structuri de asociere și operațiuni comerciale transfrontaliere.", "İkamet, çalışma izni, vatandaşlık başvurusu ve idari süreçlerin takibi.": "Rezidență, permise de muncă, cereri de cetățenie și proceduri administrative.", "Uluslararası aile dosyaları, velayet, boşanma, miras ve veraset işlemleri.": "Dosare internaționale de familie, custodie, divorț, moșteniri și succesiuni.", "Mahkeme ve icra süreçlerinde stratejik temsil, müzakere ve çözüm.": "Reprezentare strategică, negociere și soluționare în instanță și executare.", "Trafik kazaları, sigorta dosyaları ve maddi-manevi tazminat talepleri.": "Accidente rutiere, dosare de asigurare și cereri de despăgubiri materiale sau morale.",
  "Avukat · Antalya Barosu": "Avocat · Baroul Antalya", "Türkiye’de hukuk,": "Dreptul în Turcia,", "Hukuki bir mesele, kişinin bilmediği bir ülkede ve yabancı bir dilde yürüdüğünde olduğundan daha karmaşık görünebilir. Av. Ruslana Pasecinic’in çalışma yaklaşımı, bu karmaşıklığı anlaşılır bir sürece dönüştürmek üzerine kuruludur.": "O problemă juridică poate părea mai complexă atunci când se desfășoară într-o țară și într-o limbă necunoscute. Abordarea av. Ruslana Pasecinic urmărește transformarea acestei complexități într-un proces ușor de înțeles.", "Türkiye’de yaşayan, çalışan, yatırım yapan veya burada malvarlığı bulunan yabancı müvekkillerle doğrudan iletişim kurar; dosyanın hukuki yönünü, olası riskleri ve izlenecek adımları açık biçimde aktarır.": "Comunică direct cu clienții străini care locuiesc, lucrează, investesc sau dețin bunuri în Turcia, explicând clar aspectele juridice, riscurile posibile și pașii următori.", "Gayrimenkul, ticaret, göç, aile, miras ve uyuşmazlık dosyalarında; farklı hukuk alanlarının birbiriyle kesiştiği noktaları birlikte değerlendirir. Amaç yalnızca işlemi tamamlamak değil, müvekkilin kararını hukuken sağlam bir zemine oturtmaktır.": "În dosarele imobiliare, comerciale, de imigrare, familie, moștenire și litigii, analizează împreună punctele de intersecție dintre diferite ramuri de drept. Scopul nu este doar finalizarea procedurii, ci și așezarea deciziei clientului pe o bază juridică solidă.", "“Müvekkilin süreci anlaması, doğru hukuki stratejinin ayrılmaz bir parçasıdır.”": "„Înțelegerea procesului de către client este o parte inseparabilă a unei strategii juridice corecte.”",
  "Doğrudan iletişim": "Comunicare directă", "Dosyanın her aşamasında avukatla doğrudan ve kendi dilinizde iletişim.": "Comunicare directă cu avocatul, în limba dumneavoastră, în fiecare etapă.", "Özenli inceleme": "Analiză atentă", "Hazır şablonlar yerine olayın kendisine ve belgelere dayanan değerlendirme.": "Evaluare bazată pe fapte și documente, nu pe modele standard.", "Çok yönlü bakış": "Perspectivă multidisciplinară", "Türkiye hukuku ile sınır ötesi sonuçları birlikte ele alan dosya yönetimi.": "Gestionarea dosarului ținând cont atât de dreptul turc, cât și de efectele transfrontaliere.",
  "Bilgi, doğru kararın başlangıcıdır.": "Cunoașterea este începutul unei decizii corecte.", "Hukuku daha": "Dreptul,", "anlaşılır kılmak.": "mai ușor de înțeles.", "Türkiye’de yaşam, yatırım ve ticaret için güncel, sade ve uygulanabilir hukuk notları.": "Note juridice actuale, clare și practice pentru viață, investiții și afaceri în Turcia.", "Tümü": "Toate", "Yayında": "Publicat", "Taslak": "Ciornă",
  "Antalya’da,": "În Antalya,", "Türkiye’nin her yerinde.": "oriunde în Turcia.", "Telefon": "Telefon", "E-posta": "E-mail", "Adres": "Adresă", "Diller": "Limbi", "Ofis konumu": "Locația biroului", "Google Haritalar’da aç": "Deschideți în Google Maps",
};

Object.assign(en, {
  "Gayrimenkul Hukuku": "Real Estate Law", "Şirketler Hukuku": "Corporate Law", "Miras Hukuku": "Inheritance Law",
  "Türkiye’de yabancılar için taşınmaz alımında 7 kritik kontrol": "7 critical checks when foreigners buy property in Türkiye",
  "Tapu kaydından vatandaşlık uygunluğuna, satın alma kararından önce mutlaka incelenmesi gereken hukuki başlıklar.": "From title records to citizenship eligibility: the legal points that must be reviewed before a purchase decision.",
  "Türkiye’de taşınmaz satın almak, doğru hukuki kontrollerle güvenli bir yatırım sürecine dönüşür. Ancak ilan bilgileri ile resmi kayıtlar arasında fark bulunabileceği için karar yalnızca satış beyanlarına dayanarak verilmemelidir.": "Buying property in Türkiye can become a secure investment process when the right legal checks are made. Because listing information may differ from official records, a decision should never rely solely on the seller’s representations.",
  "İlk adım, tapu kaydındaki malik, takyidat, ipotek, haciz ve şerh bilgilerinin incelenmesidir. Ardından taşınmazın imar durumu, kullanım amacı, iskânı ve fiili durumu resmi kayıtlarla karşılaştırılmalıdır.": "The first step is to review the owner, encumbrances, mortgages, seizures and annotations in the title record. The property’s zoning status, intended use, occupancy permit and actual condition should then be compared with official records.",
  "Satın alma vatandaşlık veya ikamet hedefiyle yapılıyorsa değerleme, ödeme yöntemi ve devir zamanlaması birlikte planlanmalıdır. Her dosyanın koşulları farklıdır; bu nedenle sözleşme imzalanmadan önce bağımsız hukuki inceleme yapılması önem taşır.": "If the purchase is intended for citizenship or residence, valuation, payment method and transfer timing should be planned together. Every matter is different, so an independent legal review before signing is essential.",
  "Yabancı yatırımcı için Türkiye’de şirket kurmanın yol haritası": "A roadmap for foreign investors forming a company in Türkiye",
  "Şirket türü, ortaklık yapısı, izinler ve sözleşmeler: yatırım kararını sağlam bir zemine taşıyan temel adımlar.": "Company type, partnership structure, permits and contracts: essential steps for placing an investment decision on solid ground.",
  "Türkiye’de şirket kurarken yalnızca kuruluş işlemlerini değil, faaliyet modelini ve gelecekteki riskleri de birlikte değerlendirmek gerekir. Doğru şirket türü; ortakların sorumluluğunu, vergi planını ve karar alma yapısını doğrudan etkiler.": "When forming a company in Türkiye, the business model and future risks should be considered alongside incorporation formalities. The right company type directly affects partner liability, tax planning and decision-making.",
  "Ana sözleşmenin standart metinle kurulması her iş modeli için yeterli olmayabilir. İmza yetkileri, pay devri, yönetim organı ve ortaklıktan çıkış senaryoları başlangıçta açık biçimde düzenlenmelidir.": "A standard-form articles of association may not suit every business model. Signing powers, share transfers, management and exit scenarios should be clearly regulated from the outset.",
  "Yabancı ortakların çalışma ve ikamet durumu ile faaliyete özgü izinler de kuruluş takviminin parçasıdır. Sağlam bir başlangıç, sonradan çıkabilecek ortaklık uyuşmazlıklarının önemli bölümünü önler.": "The work and residence status of foreign partners and activity-specific permits also form part of the incorporation timetable. A solid start prevents many future partnership disputes.",
  "Yabancılar için miras ve veraset işlemleri nasıl yürütülür?": "How are inheritance and succession procedures handled for foreigners?",
  "Sınır ötesi miras dosyalarında yetkili makam, belge hazırlığı ve Türkiye’deki malvarlığına erişim süreci.": "The competent authority, document preparation and access to assets in Türkiye in cross-border inheritance matters.",
  "Birden fazla ülkeyle bağlantılı miras dosyalarında uygulanacak hukuk, yetkili makam ve belgelerin geçerliliği ayrı ayrı değerlendirilir. Türkiye’de bulunan taşınmazlar bakımından özel kurallar söz konusu olabilir.": "In inheritance matters connected with several countries, applicable law, competent authority and document validity are assessed separately. Special rules may apply to real estate located in Türkiye.",
  "Yabancı ülkede düzenlenen nüfus, ölüm ve miras belgelerinin apostil, tercüme ve noter süreçleri tamamlanmalıdır. Belgelerin eksik hazırlanması, veraset ilamı ve intikal işlemlerinin uzamasına yol açabilir.": "Civil status, death and inheritance documents issued abroad must complete apostille, translation and notarisation procedures. Incomplete documents may delay succession certificates and transfers.",
  "Mirasçılar Türkiye’ye gelmeden de uygun vekâletname ile birçok işlemi yürütebilir. Dosyanın başında çıkarılacak belge listesi ve işlem takvimi, hem süreyi hem de maliyeti öngörülebilir hâle getirir.": "With an appropriate power of attorney, heirs can complete many procedures without travelling to Türkiye. A document list and timetable prepared at the outset make both timing and cost more predictable.",
  "Bu konu, diğer hukuk alanlarıyla birlikte değerlendirilmesi gereken sonuçlar doğurabilir.": "This issue may have consequences that should be assessed together with other areas of law.",
});

Object.assign(ru, {
  "Gayrimenkul Hukuku": "Право недвижимости", "Şirketler Hukuku": "Корпоративное право", "Miras Hukuku": "Наследственное право",
  "Tapu ve hukuki durum incelemesi": "Проверка титула и правового статуса", "Satış ve yatırım sözleşmeleri": "Договоры купли-продажи и инвестирования", "Yatırım yoluyla vatandaşlık": "Гражданство через инвестиции", "Şirket kuruluşu ve ortaklık yapısı": "Создание компании и структура партнёрства", "Ticari sözleşmeler": "Коммерческие договоры", "Uyuşmazlık ve alacak takibi": "Споры и взыскание задолженности", "İkamet ve çalışma izinleri": "ВНЖ и разрешения на работу", "Vatandaşlık başvuruları": "Заявления на гражданство", "İdari başvuru ve itirazlar": "Административные заявления и обжалование", "Uluslararası boşanma ve velayet": "Международный развод и опека", "Mirasçılık ve intikal işlemleri": "Наследование и переход прав", "Yabancı kararların tanınması": "Признание иностранных решений", "Hukuk ve ticaret davaları": "Гражданские и коммерческие споры", "İcra ve alacak takibi": "Исполнительное производство и взыскание", "Müzakere ve arabuluculuk": "Переговоры и медиация", "Trafik kazaları": "Дорожно-транспортные происшествия", "Sigorta ve tazminat talepleri": "Страховые и компенсационные требования", "Zarar hesabı ve takip": "Расчёт ущерба и сопровождение",
  "Türkiye’de yabancılar için taşınmaz alımında 7 kritik kontrol": "7 ключевых проверок при покупке недвижимости иностранцами в Турции", "Tapu kaydından vatandaşlık uygunluğuna, satın alma kararından önce mutlaka incelenmesi gereken hukuki başlıklar.": "От записи в реестре до соответствия требованиям гражданства: правовые вопросы, которые нужно проверить до покупки.",
  "Türkiye’de taşınmaz satın almak, doğru hukuki kontrollerle güvenli bir yatırım sürecine dönüşür. Ancak ilan bilgileri ile resmi kayıtlar arasında fark bulunabileceği için karar yalnızca satış beyanlarına dayanarak verilmemelidir.": "При правильной юридической проверке покупка недвижимости в Турции может стать безопасной инвестицией. Поскольку данные объявления могут отличаться от официальных записей, решение нельзя основывать только на заявлениях продавца.",
  "İlk adım, tapu kaydındaki malik, takyidat, ipotek, haciz ve şerh bilgilerinin incelenmesidir. Ardından taşınmazın imar durumu, kullanım amacı, iskânı ve fiili durumu resmi kayıtlarla karşılaştırılmalıdır.": "Первый шаг — проверить собственника, обременения, ипотеку, аресты и отметки в реестре. Затем следует сопоставить зонирование, назначение, разрешение на эксплуатацию и фактическое состояние объекта с официальными данными.",
  "Satın alma vatandaşlık veya ikamet hedefiyle yapılıyorsa değerleme, ödeme yöntemi ve devir zamanlaması birlikte planlanmalıdır. Her dosyanın koşulları farklıdır; bu nedenle sözleşme imzalanmadan önce bağımsız hukuki inceleme yapılması önem taşır.": "Если покупка связана с гражданством или ВНЖ, оценку, способ оплаты и сроки передачи следует планировать совместно. Обстоятельства каждого дела различаются, поэтому до подписания договора важна независимая юридическая проверка.",
  "Yabancı yatırımcı için Türkiye’de şirket kurmanın yol haritası": "План создания компании в Турции для иностранного инвестора", "Şirket türü, ortaklık yapısı, izinler ve sözleşmeler: yatırım kararını sağlam bir zemine taşıyan temel adımlar.": "Форма компании, структура партнёрства, разрешения и договоры: основные шаги для надёжной инвестиции.",
  "Türkiye’de şirket kurarken yalnızca kuruluş işlemlerini değil, faaliyet modelini ve gelecekteki riskleri de birlikte değerlendirmek gerekir. Doğru şirket türü; ortakların sorumluluğunu, vergi planını ve karar alma yapısını doğrudan etkiler.": "При создании компании в Турции вместе с регистрационными процедурами необходимо оценить бизнес-модель и будущие риски. Выбор формы компании напрямую влияет на ответственность партнёров, налоговое планирование и принятие решений.", "Ana sözleşmenin standart metinle kurulması her iş modeli için yeterli olmayabilir. İmza yetkileri, pay devri, yönetim organı ve ortaklıktan çıkış senaryoları başlangıçta açık biçimde düzenlenmelidir.": "Стандартный текст устава подходит не каждой бизнес-модели. Полномочия подписи, передача долей, органы управления и сценарии выхода из партнёрства должны быть чётко урегулированы с самого начала.", "Yabancı ortakların çalışma ve ikamet durumu ile faaliyete özgü izinler de kuruluş takviminin parçasıdır. Sağlam bir başlangıç, sonradan çıkabilecek ortaklık uyuşmazlıklarının önemli bölümünü önler.": "Статус работы и проживания иностранных партнёров, а также специальные разрешения входят в график создания компании. Надёжное начало предотвращает значительную часть будущих партнёрских споров.",
  "Yabancılar için miras ve veraset işlemleri nasıl yürütülür?": "Как оформляются наследственные процедуры для иностранцев?", "Sınır ötesi miras dosyalarında yetkili makam, belge hazırlığı ve Türkiye’deki malvarlığına erişim süreci.": "Компетентный орган, подготовка документов и доступ к активам в Турции в трансграничных наследственных делах.",
  "Birden fazla ülkeyle bağlantılı miras dosyalarında uygulanacak hukuk, yetkili makam ve belgelerin geçerliliği ayrı ayrı değerlendirilir. Türkiye’de bulunan taşınmazlar bakımından özel kurallar söz konusu olabilir.": "В наследственных делах, связанных с несколькими странами, отдельно оцениваются применимое право, компетентный орган и действительность документов. Для недвижимости в Турции могут действовать специальные правила.", "Yabancı ülkede düzenlenen nüfus, ölüm ve miras belgelerinin apostil, tercüme ve noter süreçleri tamamlanmalıdır. Belgelerin eksik hazırlanması, veraset ilamı ve intikal işlemlerinin uzamasına yol açabilir.": "Документы гражданского состояния, смерти и наследования, выданные за рубежом, должны пройти апостиль, перевод и нотариальное оформление. Неполный комплект может затянуть получение свидетельства и переход прав.", "Mirasçılar Türkiye’ye gelmeden de uygun vekâletname ile birçok işlemi yürütebilir. Dosyanın başında çıkarılacak belge listesi ve işlem takvimi, hem süreyi hem de maliyeti öngörülebilir hâle getirir.": "При надлежащей доверенности наследники могут выполнить многие процедуры без приезда в Турцию. Перечень документов и график действий в начале дела делают сроки и расходы предсказуемыми.",
  "Bu konu, diğer hukuk alanlarıyla birlikte değerlendirilmesi gereken sonuçlar doğurabilir.": "Этот вопрос может иметь последствия, которые следует оценивать вместе с другими областями права.",
});

Object.assign(ro, {
  "Gayrimenkul Hukuku": "Drept imobiliar", "Şirketler Hukuku": "Drept corporativ", "Miras Hukuku": "Drept succesoral",
  "Tapu ve hukuki durum incelemesi": "Verificarea titlului și a situației juridice", "Satış ve yatırım sözleşmeleri": "Contracte de vânzare și investiții", "Yatırım yoluyla vatandaşlık": "Cetățenie prin investiție", "Şirket kuruluşu ve ortaklık yapısı": "Înființarea companiei și structura asociaților", "Ticari sözleşmeler": "Contracte comerciale", "Uyuşmazlık ve alacak takibi": "Litigii și recuperarea creanțelor", "İkamet ve çalışma izinleri": "Permise de ședere și muncă", "Vatandaşlık başvuruları": "Cereri de cetățenie", "İdari başvuru ve itirazlar": "Cereri și contestații administrative", "Uluslararası boşanma ve velayet": "Divorț internațional și custodie", "Mirasçılık ve intikal işlemleri": "Succesiune și transfer", "Yabancı kararların tanınması": "Recunoașterea hotărârilor străine", "Hukuk ve ticaret davaları": "Litigii civile și comerciale", "İcra ve alacak takibi": "Executare și recuperarea creanțelor", "Müzakere ve arabuluculuk": "Negociere și mediere", "Trafik kazaları": "Accidente rutiere", "Sigorta ve tazminat talepleri": "Cereri de asigurare și despăgubire", "Zarar hesabı ve takip": "Calculul prejudiciului și urmărire",
  "Türkiye’de yabancılar için taşınmaz alımında 7 kritik kontrol": "7 verificări esențiale pentru străinii care cumpără proprietăți în Turcia", "Tapu kaydından vatandaşlık uygunluğuna, satın alma kararından önce mutlaka incelenmesi gereken hukuki başlıklar.": "De la registrul funciar la eligibilitatea pentru cetățenie: aspectele juridice ce trebuie verificate înainte de cumpărare.",
  "Türkiye’de taşınmaz satın almak, doğru hukuki kontrollerle güvenli bir yatırım sürecine dönüşür. Ancak ilan bilgileri ile resmi kayıtlar arasında fark bulunabileceği için karar yalnızca satış beyanlarına dayanarak verilmemelidir.": "Cumpărarea unei proprietăți în Turcia poate deveni o investiție sigură dacă sunt efectuate verificările juridice corecte. Deoarece informațiile din anunț pot diferi de evidențele oficiale, decizia nu trebuie bazată exclusiv pe declarațiile vânzătorului.",
  "İlk adım, tapu kaydındaki malik, takyidat, ipotek, haciz ve şerh bilgilerinin incelenmesidir. Ardından taşınmazın imar durumu, kullanım amacı, iskânı ve fiili durumu resmi kayıtlarla karşılaştırılmalıdır.": "Primul pas este verificarea proprietarului, sarcinilor, ipotecilor, sechestrelor și mențiunilor din registrul funciar. Apoi, regimul urbanistic, destinația, autorizația de utilizare și starea de fapt trebuie comparate cu evidențele oficiale.",
  "Satın alma vatandaşlık veya ikamet hedefiyle yapılıyorsa değerleme, ödeme yöntemi ve devir zamanlaması birlikte planlanmalıdır. Her dosyanın koşulları farklıdır; bu nedenle sözleşme imzalanmadan önce bağımsız hukuki inceleme yapılması önem taşır.": "Dacă achiziția urmărește cetățenia sau rezidența, evaluarea, metoda de plată și momentul transferului trebuie planificate împreună. Fiecare dosar este diferit, astfel că o verificare juridică independentă înainte de semnare este esențială.",
  "Yabancı yatırımcı için Türkiye’de şirket kurmanın yol haritası": "Planul investitorului străin pentru înființarea unei companii în Turcia", "Şirket türü, ortaklık yapısı, izinler ve sözleşmeler: yatırım kararını sağlam bir zemine taşıyan temel adımlar.": "Tipul companiei, structura asociaților, autorizațiile și contractele: pașii esențiali pentru o investiție solidă.",
  "Türkiye’de şirket kurarken yalnızca kuruluş işlemlerini değil, faaliyet modelini ve gelecekteki riskleri de birlikte değerlendirmek gerekir. Doğru şirket türü; ortakların sorumluluğunu, vergi planını ve karar alma yapısını doğrudan etkiler.": "La înființarea unei companii în Turcia trebuie analizate atât formalitățile, cât și modelul de activitate și riscurile viitoare. Tipul corect de companie influențează direct răspunderea asociaților, planificarea fiscală și procesul decizional.", "Ana sözleşmenin standart metinle kurulması her iş modeli için yeterli olmayabilir. İmza yetkileri, pay devri, yönetim organı ve ortaklıktan çıkış senaryoları başlangıçta açık biçimde düzenlenmelidir.": "Un act constitutiv standard poate să nu fie suficient pentru orice model de afaceri. Drepturile de semnătură, transferul părților sociale, conducerea și scenariile de ieșire trebuie reglementate clar de la început.", "Yabancı ortakların çalışma ve ikamet durumu ile faaliyete özgü izinler de kuruluş takviminin parçasıdır. Sağlam bir başlangıç, sonradan çıkabilecek ortaklık uyuşmazlıklarının önemli bölümünü önler.": "Statutul de muncă și ședere al asociaților străini, precum și autorizațiile specifice activității fac parte din calendarul înființării. Un început solid previne multe litigii ulterioare între asociați.",
  "Yabancılar için miras ve veraset işlemleri nasıl yürütülür?": "Cum se desfășoară procedurile de moștenire pentru străini?", "Sınır ötesi miras dosyalarında yetkili makam, belge hazırlığı ve Türkiye’deki malvarlığına erişim süreci.": "Autoritatea competentă, pregătirea documentelor și accesul la bunurile din Turcia în succesiunile transfrontaliere.",
  "Birden fazla ülkeyle bağlantılı miras dosyalarında uygulanacak hukuk, yetkili makam ve belgelerin geçerliliği ayrı ayrı değerlendirilir. Türkiye’de bulunan taşınmazlar bakımından özel kurallar söz konusu olabilir.": "În succesiunile legate de mai multe state, legea aplicabilă, autoritatea competentă și valabilitatea documentelor sunt analizate separat. Pentru imobilele din Turcia pot exista reguli speciale.", "Yabancı ülkede düzenlenen nüfus, ölüm ve miras belgelerinin apostil, tercüme ve noter süreçleri tamamlanmalıdır. Belgelerin eksik hazırlanması, veraset ilamı ve intikal işlemlerinin uzamasına yol açabilir.": "Actele de stare civilă, deces și moștenire emise în străinătate trebuie apostilate, traduse și autentificate. Documentele incomplete pot întârzia certificatul de moștenitor și transferul.", "Mirasçılar Türkiye’ye gelmeden de uygun vekâletname ile birçok işlemi yürütebilir. Dosyanın başında çıkarılacak belge listesi ve işlem takvimi, hem süreyi hem de maliyeti öngörülebilir hâle getirir.": "Cu o procură adecvată, moștenitorii pot îndeplini multe proceduri fără a veni în Turcia. Lista documentelor și calendarul stabilite de la început fac durata și costurile mai previzibile.",
  "Bu konu, diğer hukuk alanlarıyla birlikte değerlendirilmesi gereken sonuçlar doğurabilir.": "Această problemă poate produce efecte care trebuie analizate împreună cu alte domenii de drept.",
});

export const translations: Record<Exclude<SiteLanguage, "tr">, Record<string, string>> = { en, ru, ro };
